name: CI Pipeline

on:
  push:
      branches:
        - main
        - deploy

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: javaHelloWorldApp.java


      - name: algo mas
        run: echo hola mundo